'''
A RANDOM DISTRIBUTION IS A SET OF RANDOM NUMBER THAT A CERTAIN PROBABILITY DENSITY FUNCTION 

PROBABILITY DENSITY FUNCTION : A FUNCTION THAT DESCRIBES A CONTINUES PROBABILITY I.E PROBABILITY OF ALL VALUES IN AN ARRAY 

THE PROBABILITY IS SET BY NUMBER BETWEEN 0 OR 1 WHERE 0 MEANS THAT THE VALUE WILL NEVER OCCUR 1 MEANS THAT THE VALUE WILL ALWAYS OCCUR :
'''

# GENERATE A 1D ARRAY ACCORDING  TO 100 VALUES WHERE EACH VALUE HAS TO BE 3,5,7,9:
from numpy import random 
x = random .choice([2,4,6,8],p=[0.1,0.3,0.6,0.0], size=(100)) # all probability sum ia 1 :
print ("set probability in fix element : ",x)

# SAME EXAMPLE ABOVE AS ABOVE BUT RETURN A 2D ARRAY WITH 3 ROWS EACH CONTAINING 5 VALUES :

x = random .choice([4,7,9,2],p=[0.4,0.2, 0.2,0.2],size=(3,5))
print ("print 2-d array :",x)

